### ISSUE TITLE
Vue 2 or 3?

### ISSUE THREAD

**Issue by mesqueeb** [adamdehaven/vue-custom-tooltip#1]
Is there any guidance on which version to use for Vue 2 and Vue 3?

**Comment by adamdehaven** [comment]
This repo currently only has a single version. I have a version ready that is compatible with Vue 3 (and uses TypeScript) but I'm unsure if I want to integrate them both into the same repo on different branches (e.g. a `next` branch). 

Any thoughts?

**Comment by mesqueeb** [comment]
@adamdehaven I think just a major update sounds good.
As long as it's clear from the readme, I don't think anyone will have an issue.
You could write something like:

### Vue Compatibility

- Vue 2: use version 1.x (last update is v1.3.2)
- Vue 3: use version 2.x

**Comment by adamdehaven** [comment]
@mesqueeb I just released version `2.x` of the plugin which now supports Vue 3 and TypeScript. 

Check it out and let me know if you have any issues. Instructions are in the [README](https://github.com/adamdehaven/vue-custom-tooltip)
