### ISSUE TITLE
[Bug Report] Custom class not applied (vue 3)

### ISSUE THREAD

**Issue by daronspence** [adamdehaven/vue-custom-tooltip#10]
**Describe the bug**
`class` attribute is not added/merged when using `version@next`

**To Reproduce**
1. Install `@next`
2. Create a single component that imports the package
3. Try to apply a new `class` attribute; bound or otherwise, does not matter
4. Assert the extra classes are not added to the element

**Expected behavior**
A class is added to the rendered component.

My file `Tooltip.vue`
```vue
<template>
  <VueCustomTooltip :label="content" :multiline="true" class="my-class-that-is-not-applied">
    <slot />
  </VueCustomTooltip>
</template>

<script>
import VueCustomTooltip from '@adamdehaven/vue-custom-tooltip';

export default {
  components: {
    VueCustomTooltip,
  },
  props: {
    content: {
      type: String,
      required: true,
    },
  },
};
```

**Comment by adamdehaven** [comment]
Good catch @Daronspence. I just pushed a fix to this repo, and published `2.5.1` on npm. Update your local package and let me know if this resolves the issue for you. Thanks!

**Comment by daronspence** [comment]
Works great! Thanks for knocking that out. Idk why it's so tough to find a good Vue 3 compatible tooltip library. Thanks for updating yours!

**Comment by adamdehaven** [comment]
No problem. If you ever have other feature suggestions, etc. just open a new issue.
