### ISSUE TITLE
[Feature Request] Adding styles to label

### ISSUE THREAD

**Issue by iamshulz** [adamdehaven/vue-custom-tooltip#12]
**Is your feature request related to a problem? Please describe.**
I wanted to add styles within the tooltip but it displays the html tags instead.
![image](https://user-images.githubusercontent.com/20100579/132076382-b495aa35-aeec-4481-8842-f0f2b7b2007b.png)

**Describe the solution you'd like**
Would it be possible to display styles inside the tooltip such as icon simple html will do (color of specific text, bold letter, etc..)

**Describe anything you've already tried**
I've tried adding tags to the label but it would also display the code tag.

**Comment by adamdehaven** [comment]
The content is added inside the tooltip via CSS, meaning HTML cannot be passed/rendered into the tooltip itself; only text is valid.
