### ISSUE TITLE
[Feature Request] Allow HTML in label or `$ref` to show some other element as the tooltip

### ISSUE THREAD

**Issue by ManasMadrecha** [adamdehaven/vue-custom-tooltip#16]
**Is your feature request related to a problem? Please describe.**
Only adding text in label is very restrictive. 

**Describe the solution you'd like**
Give an option to add HTML to the label so as to add components in the tooltip. Also, allow an option to give the reference to some other element in DOM so that tooltips don't clutter the markdown. 

**Describe anything you've already tried**

**Additional context**

**Comment by adamdehaven** [comment]
This plugin is really just meant to be a tooltip for text only. The functionality you're describing is more suited for a Popover, whereby you can display any sort of HTML/component as the content.

You may want to look into [Popper](https://popper.js.org/) or a similar Vue implementation.
