### ISSUE TITLE
[Feature Request] A prop to change the position of the tooltip

### ISSUE THREAD

**Issue by ahsan-a** [adamdehaven/vue-custom-tooltip#3]
Hi, i'd just like to start off by saying thank you for this package! It's by far one of the best I've tried.

I think a useful feature would be to be able to change the position of the tooltip. By default it is at the top, but a prop to change the position would be useful.

**Comment by adamdehaven** [comment]
Actually, there is an existing [position prop](https://github.com/adamdehaven/vue-custom-tooltip#position) available to do just what you're asking!

Here's an example:

```html
<VueCustomTooltip label="This is the tooltip text" position="is-right">a tooltip</VueCustomTooltip>
```

The allowed values for the `position` prop are shown below:

```js
'is-top' // default
'is-right'
'is-bottom'
'is-left'
```

**Comment by ahsan-a** [comment]
Oh wow, thanks! Turns out i'm just blind and completely missed the bit in the readme 😆
