### ISSUE TITLE
Vue 3: [Vue warn]: Component is missing template or render function. 

### ISSUE THREAD

**Issue by alinkedd** [adamdehaven/vue-custom-tooltip#4]
Initializing the component directly in the file leads to warning 'Component is missing template or render function.'

**To Reproduce**
1. Get vue 3 cli project
2. Install next version of package, e.g. 'yarn add @adamdehaven/vue-custom-tooltip@next'
3. Register component as [described](https://www.adamdehaven.com/blog/how-to-install-a-customizable-vue-tooltip-component-to-create-help-text-and-abbreviations/#in-component-locally-available)
4. Use component as [described](https://www.adamdehaven.com/blog/how-to-install-a-customizable-vue-tooltip-component-to-create-help-text-and-abbreviations/#usage) in `<!-- With element(s) -->` section
5. See error in console `Component is missing template or render function.`

**Expected behavior**
No warning, tooltip and its component are rendered.

**Desktop:**
 - OS: Windows 10 (running in WSL 2 on Ubuntu 20.04)
 - Browser: Chrome 92, Firefox 90
 - Package Version: 2.0.4
 - Environment:
 Vue: 3.0.11,
 @vue/cli: 4.5.13 with TS and Vue SFC

**Additional context**
Global component initialization works fine, only in-component one fails.

And thanks for maintaining this repo and updating it to Vue 3.

**Comment by adamdehaven** [comment]
@alinkedd thanks! I can replicate what you're seeing and hope to have some time to look into it this weekend. In the meantime, you can [register the component globally in your entry file as described here](https://www.adamdehaven.com/blog/how-to-install-a-customizable-vue-tooltip-component-to-create-help-text-and-abbreviations/#vuejs-globally-available---recommended) and it should work properly.

**Comment by adamdehaven** [comment]
@alinkedd I've updated the plugin (and documentation); however, for Vue 3 the recommended install has changed to a global installation. This probably makes more sense for most use-cases anyway. The component is extremely light, so just initialize in your entry file. Thanks for pointing this out.

**Comment by adamdehaven** [comment]
@alinkedd I was actually able to fix this and just released a [new version, 2.5.0, located here](https://github.com/adamdehaven/vue-custom-tooltip/releases/tag/v2.5.0).

Update the plugin in your project to version 2.5.x, then, the import should work as expected.
